import React from 'react';
import ThemeSwitcher from "./ThemeSwitcher";
import Theme from "./Theme";
import themes from "./colors";
import Autocomplete from "./Autocomplete";
import Button from "./Button";
import Checkbox from "./Checkbox";
import Dropdown from "./Dropdown";
import GlobalStyles from "./GlobalStyles";
import Icon from "./Icon";
import Input from "./Input";
import MultipleInput from "./MultipleInput";
import Password from "./Password";
import Radiobutton from "./Radiobutton";
import Tooltip from "./Tooltip";

module.exports.Theme = Theme;
module.exports.themes = themes;
module.exports.ThemeSwitcher = ThemeSwitcher;
module.exports.Autocomplete = Autocomplete;
module.exports.Button = Button;
module.exports.Checkbox = Checkbox;
module.exports.Dropdown = Dropdown;
module.exports.GlobalStyles = GlobalStyles;
module.exports.Icon = Icon;
module.exports.Input = Input;
module.exports.MultipleInput = MultipleInput;
module.exports.Password = Password;
module.exports.Radiobutton = Radiobutton;
module.exports.Tooltip = Tooltip;
